### ISSUE TITLE
Not working in CF Worker

### ISSUE THREAD

**Issue by Nytrm** [neurocode-io/azure-sas-token#56]
This package using ```Buffer```, that is not defined because CF Workers are based on web platform APIs instead.

The web platform alternative to ```Buffer``` is ```Uint8Array```

**Comment by Nytrm** [comment]
`const base64ToArrayBuffer = (b64)  => {
    var byteString = atob(b64);
    var byteArray = new Uint8Array(byteString.length);
    for(var i=0; i < byteString.length; i++) {
        byteArray[i] = byteString.charCodeAt(i);
    }

    return byteArray;
}

const arrayBufferToBase64 = (arrayBuffer) => {
    var byteArray = new Uint8Array(arrayBuffer);
    var byteString = '';
    for(var i=0; i < byteArray.byteLength; i++) {
        byteString += String.fromCharCode(byteArray[i]);
    }
    var b64 = btoa(byteString);

    return b64;
}`

can be fixed by changing ```Buffer.from(accountKey, 'base64')``` with ```base64ToArrayBuffer(accountKey)```
and ```Buffer.from(digest).toString('base64')``` to ```arrayBufferToBase64(digest)```

**Comment by donchev7** [comment]
Hi, the package uses Buffer thats true. Even though Buffer is not part of the Browser API it works on CF. The library is being used in production for a couple of years now. I encourage you to test it for yourself and you will see that CF abstracted Buffer themselves and implemented Buffer handling.

**Comment by donchev7** [comment]
You were actually right. When I initialise a new CF worker and install this library and use it I get an error. 
Thanks for letting me know!

I created a PR [here](https://github.com/neurocode-io/azure-sas-token/pull/64) with a fix.
